Repository SOPT-29th-Joint-Seminar-3/client-iOS, pull requests merged in 2021-12, with the labels that each got.

#24 Feature/play list detail service
  Client-iOS/Client-iOS.xcodeproj/project.pbxproj
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/Models/PlaylistDetailModel.swift
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/PlaylistDetailVC+DataSource.swift
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/PlaylistDetailVC.swift
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/Services/PlaylistDetailService.swift
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/Views/AlbumCoverCVC.swift
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/Views/AlbumCoverCVC.xib
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/Views/AlbumTrackCVC.swift
Labels: yangsubinn💦

#25 Feature/get my play list service
  Client-iOS/Client-iOS.xcodeproj/project.pbxproj
  Client-iOS/Client-iOS/Scenes/MyMusic/MyMusicVC+DataSource.swift
  Client-iOS/Client-iOS/Scenes/MyMusic/MyMusicVC.swift
  Client-iOS/Client-iOS/Scenes/MyMusic/MyPlayListForm.swift
  Client-iOS/Client-iOS/Scenes/MyMusic/Services/GetMyMusicService.swift
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/MyPlayListCVC.swift
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/QuickMenuCV.swift
Labels: jungbin

#28 Feature/create playlist api
  Client-iOS/Client-iOS.xcodeproj/project.pbxproj
  Client-iOS/Client-iOS/Extensions/UIApplication+.swift
  Client-iOS/Client-iOS/Extensions/UIView+.swift
  Client-iOS/Client-iOS/Scenes/MyMusic/Services/PlaylistService+Creation.swift
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/MyPlayListHeaderView.swift
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/MyPlayListHeaderView.xib
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/PlaylistPopUpView.swift
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/PlaylistPopUpView.xib
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/Models/PlaylistDetailModel.swift
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/PlaylistDetailVC+DataSource.swift
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/Services/PlaylistDetailService.swift
Labels: taeeehyeon 👾, 내음악뷰 알림팝업

#29 Feature/bookmark playlist api
  Client-iOS/Client-iOS.xcodeproj/project.pbxproj
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_star_fill.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_star_fill.imageset/icn_star_fill.png
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/Models/PlaylistBookmarkModel.swift
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/Services/PlaylistService+Bookmark.swift
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/Views/AlbumCoverCVC.swift
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/Views/AlbumCoverCVC.xib
Labels: taeeehyeon 👾, 플레이리스트 디테일뷰

#33 Fix: PlaylistDetail 수록곡 레이아웃 수정
  Client-iOS/Client-iOS.xcodeproj/project.pbxproj
  Client-iOS/Client-iOS/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Client-iOS/Client-iOS/Scenes/MyMusic/Models/MyPlayListForm.swift
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/Models/AlbumTrackListForm.swift
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/PlaylistDetailVC+Layout.swift
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/Views/PlaylistViewSample.swift
Labels: bug, jungbin

#35 Move/#34
  Client-iOS/Client-iOS.xcodeproj/project.pbxproj
  Client-iOS/Client-iOS/Resources/Base.lproj/Main.storyboard
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/Cells/MyPlayListCVC.swift
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/Cells/MyPlayListFooterView.swift
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/Cells/MyPlayListHeaderView.swift
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/Cells/PlayStatusView.swift
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/Cells/PlaylistPopUpView.swift
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/Cells/QuickMenuCV.swift
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/Cells/QuickMenuCVC.swift
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/MyMusicViewSample.swift
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/TestVC.swift
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/Xibs/MyPlayListCVC.xib
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/Xibs/MyPlayListFooterView.xib
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/Xibs/MyPlayListHeaderView.xib
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/Xibs/PlayStatusView.xib
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/Xibs/PlaylistPopUpView.xib
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/Xibs/QuickMenuCV.xib
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/Xibs/QuickMenuCVC.xib
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/Models/AlbumTrackListForm.swift
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/Views/Cells/AlbumCoverCVC.swift
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/Views/Cells/AlbumTrackCVC.swift
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/Views/Cells/AlbumTrackHeaderView.swift
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/Views/Xibs/AlbumCoverCVC.xib
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/Views/Xibs/AlbumTrackCVC.xib
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/Views/Xibs/AlbumTrackHeaderView.xib
Labels: yangsubinn💦

#36 Fix: MyPlayListCVC Image Name 오류 해결
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/Cells/MyPlayListCVC.swift
Labels: bug, jungbin
