Repository SOPT-29th-Joint-Seminar-3/client-iOS, pull requests merged in 2021-11, with the labels that each got.

#9 Add: MyPlayList TVC 추가
  Client-iOS/Client-iOS.xcodeproj/project.pbxproj
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_1.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_1.imageset/cover_1.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_1.imageset/cover_1@2x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_1.imageset/cover_1@3x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_10.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_10.imageset/cover_10.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_10.imageset/cover_10@2x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_10.imageset/cover_10@3x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_2.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_2.imageset/cover_2.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_2.imageset/cover_2@2x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_2.imageset/cover_2@3x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_3.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_3.imageset/cover_3.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_3.imageset/cover_3@2x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_3.imageset/cover_3@3x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_4.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_4.imageset/cover_4.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_4.imageset/cover_4@2x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_4.imageset/cover_4@3x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_5.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_5.imageset/cover_5.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_5.imageset/cover_5@2x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_5.imageset/cover_5@3x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_6.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_6.imageset/cover_6.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_6.imageset/cover_6@2x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_6.imageset/cover_6@3x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_7.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_7.imageset/cover_7.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_7.imageset/cover_7@2x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_7.imageset/cover_7@3x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_8.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_8.imageset/cover_8.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_8.imageset/cover_8@2x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_8.imageset/cover_8@3x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_9.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_9.imageset/cover_9.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_9.imageset/cover_9@2x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/albumCover/cover_9.imageset/cover_9@3x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/grey_2.colorset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_bigplay.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_bigplay.imageset/icn_bigplay.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_bigplay.imageset/icn_bigplay@2x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_bigplay.imageset/icn_bigplay@3x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_plus.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_plus.imageset/icn_plus.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_plus.imageset/icn_plus@2x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_plus.imageset/icn_plus@3x.png
  Client-iOS/Client-iOS/Scenes/MyMusic/MyPlayListForm.swift
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/MyPlayListTVC.swift
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/MyPlayListTVC.xib
Labels: jungbin

#11 Add: 퀵메뉴 컬렉션뷰 생성
  Client-iOS/Client-iOS.xcodeproj/project.pbxproj
  Client-iOS/Client-iOS/Common/Typography.swift
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_heart.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_heart.imageset/icn_heart.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_keep.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_keep.imageset/icn_keep.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_play.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_play.imageset/icn_play.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_time.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_time.imageset/icn_time.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/quickMenuCover_1.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/quickMenuCover_1.imageset/quickMenuCover_1.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/quickMenuCover_2.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/quickMenuCover_2.imageset/quickMenuCover_2.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/quickMenuCover_3.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/quickMenuCover_3.imageset/quickMenuCover_3.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/quickMenuCover_4.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/quickMenuCover_4.imageset/quickMenuCover_4.png
  Client-iOS/Client-iOS/Resources/Base.lproj/Main.storyboard
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/QuickMenuCV.swift
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/QuickMenuCV.xib
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/QuickMenuCVC.swift
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/QuickMenuCVC.xib
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/TestVC.swift
Labels: yangsubinn💦

#12 Add: AlbumCoverCVC 생성
  Client-iOS/Client-iOS.xcodeproj/project.pbxproj
  Client-iOS/Client-iOS/Resources/Assets.xcassets/btn_back.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/btn_back.imageset/btn_back.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/btn_back.imageset/btn_back@2x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/btn_back.imageset/btn_back@3x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/btn_play.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/btn_play.imageset/btn_play.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/headerAlbumCover/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/headerAlbumCover/headerCover_1.imageset/1.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/headerAlbumCover/headerCover_1.imageset/1@2x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/headerAlbumCover/headerCover_1.imageset/1@3x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/headerAlbumCover/headerCover_1.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/headerAlbumCover/headerCover_2.imageset/2.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/headerAlbumCover/headerCover_2.imageset/2@2x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/headerAlbumCover/headerCover_2.imageset/2@3x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/headerAlbumCover/headerCover_2.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/headerAlbumCover/headerCover_3.imageset/3.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/headerAlbumCover/headerCover_3.imageset/3@2x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/headerAlbumCover/headerCover_3.imageset/3@3x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/headerAlbumCover/headerCover_3.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/headerAlbumCover/headerCover_4.imageset/4.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/headerAlbumCover/headerCover_4.imageset/4@2x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/headerAlbumCover/headerCover_4.imageset/4@3x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/headerAlbumCover/headerCover_4.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/headerAlbumCover/headerCover_5.imageset/5.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/headerAlbumCover/headerCover_5.imageset/5@2x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/headerAlbumCover/headerCover_5.imageset/5@3x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/headerAlbumCover/headerCover_5.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_edit.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_edit.imageset/icn_edit.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_music.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_music.imageset/icn_music.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_right_arrow.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_right_arrow.imageset/icn_right_arrow.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_share.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_share.imageset/icn_share.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_star.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_star.imageset/icn_star.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/topBackImage.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/topBackImage.imageset/topBackImage.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/topBackImage.imageset/topBackImage@2x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/topBackImage.imageset/topBackImage@3x.png
  Client-iOS/Client-iOS/Resources/Base.lproj/Main.storyboard
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/TestVC.swift
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/Views/AlbumCoverCVC.swift
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/Views/AlbumCoverCVC.xib
Labels: yangsubinn💦

#13 Chore: 네비게이션(Navigation) 세팅
  Client-iOS/Client-iOS.xcodeproj/project.pbxproj
  Client-iOS/Client-iOS/Common/Base/BaseVC.swift
  Client-iOS/Client-iOS/Common/Image.swift
  Client-iOS/Client-iOS/Scenes/MyMusic/MyMusicVC.swift
  Client-iOS/Client-iOS/Scenes/TabBar/MainTabBar.swift
  Client-iOS/Client-iOS/Scenes/TabBar/MainTabBarController.swift
  Client-iOS/Client-iOS/Scenes/TabBar/PreparingVC.swift
  Client-iOS/Client-iOS/Supports/SceneDelegate.swift
Labels: taeeehyeon 👾, chore

#14 Add: MyPlayListHeaderView 생성
  Client-iOS/Client-iOS.xcodeproj/project.pbxproj
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_down.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_down.imageset/icn_down.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_down.imageset/icn_down@2x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_down.imageset/icn_down@3x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_imgToList.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_imgToList.imageset/icn_imgToList.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_imgToList.imageset/icn_imgToList@2x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_imgToList.imageset/icn_imgToList@3x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_newPlayList.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_newPlayList.imageset/icn_newPlayList.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_newPlayList.imageset/icn_newPlayList@2x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_newPlayList.imageset/icn_newPlayList@3x.png
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/MyPlayListHeaderView.swift
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/MyPlayListHeaderView.xib
Labels: jungbin

#18 Chore: 내 음악뷰, 음악 상세뷰 UI 세팅
  Client-iOS/Client-iOS.xcodeproj/project.pbxproj
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_largePlay.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_largePlay.imageset/polygon4.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_largePlay.imageset/polygon4@2x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_largePlay.imageset/polygon4@3x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_next.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_next.imageset/union.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_next.imageset/union@2x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_next.imageset/union@3x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_playStatusList.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_playStatusList.imageset/union.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_playStatusList.imageset/union@2x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_playStatusList.imageset/union@3x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_previous.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_previous.imageset/union.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_previous.imageset/union@2x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/icn_previous.imageset/union@3x.png
  Client-iOS/Client-iOS/Scenes/MyMusic/MyMusicSection.swift
  Client-iOS/Client-iOS/Scenes/MyMusic/MyMusicVC+DataSource.swift
  Client-iOS/Client-iOS/Scenes/MyMusic/MyMusicVC+Layout.swift
  Client-iOS/Client-iOS/Scenes/MyMusic/MyMusicVC.storyboard
  Client-iOS/Client-iOS/Scenes/MyMusic/MyMusicVC.swift
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/MyPlayListCVC.xib
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/MyPlayListHeaderView.swift
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/MyPlayListHeaderView.xib
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/PlayStatusView.swift
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/PlayStatusView.xib
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/TestVC.swift
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/PlaylistDetailSection.swift
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/PlaylistDetailVC+DataSource.swift
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/PlaylistDetailVC+Layout.swift
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/PlaylistDetailVC.storyboard
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/PlaylistDetailVC.swift
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/Views/AlbumCoverCVC.swift
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/Views/AlbumCoverCVC.xib
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/Views/AlbumTrackHeaderView.swift
  Client-iOS/Client-iOS/Scenes/PlaylistDetail/Views/AlbumTrackHeaderView.xib
  Client-iOS/Client-iOS/Scenes/TabBar/MainTabBarController.swift
  Client-iOS/Client-iOS/Scenes/TabBar/PreparingVC.swift
Labels: taeeehyeon 👾, chore

#20 Feat: 음악 리스트 접고 펼치는 인터랙션
  Client-iOS/Client-iOS.xcodeproj/project.pbxproj
  Client-iOS/Client-iOS/Resources/Assets.xcassets/btn_fold.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/btn_fold.imageset/group33700.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/btn_fold.imageset/group33700@2x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/btn_fold.imageset/group33700@3x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/btn_unfold.imageset/Contents.json
  Client-iOS/Client-iOS/Resources/Assets.xcassets/btn_unfold.imageset/group33699.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/btn_unfold.imageset/group33699@2x.png
  Client-iOS/Client-iOS/Resources/Assets.xcassets/btn_unfold.imageset/group33699@3x.png
  Client-iOS/Client-iOS/Scenes/MyMusic/MyMusicVC+DataSource.swift
  Client-iOS/Client-iOS/Scenes/MyMusic/MyMusicVC+Layout.swift
  Client-iOS/Client-iOS/Scenes/MyMusic/MyMusicVC.swift
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/MyPlayListFooterView.swift
  Client-iOS/Client-iOS/Scenes/MyMusic/Views/MyPlayListFooterView.xib
Labels: taeeehyeon 👾

#22 Add: 네트워킹 세팅
  Client-iOS/Client-iOS.xcodeproj/project.pbxproj
  Client-iOS/Client-iOS/Network/APIConstants.swift
  Client-iOS/Client-iOS/Network/NetworkResult.swift
Labels: question, jungbin
